# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9d94daf71fb2d48fbbad1f23117b040d2605843203eac82a211d20b0fc8a3eab84171aef484f86cc10d8fda89a553e8cfba7b6c8b018792ff02a719abc38297

test:
  secret_key_base: a76a101507497bfbaccf8b07bf4457e4093507dc495ee0448bc92942b9302540144be29f27e3fd3615925e8aab2003b193acdf09df336f92ce68f6119ed56ea7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
